[package]
name = "ASTEROIDS"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.33.3"
minifb = "0.28.0"
rand = "0.9.2"
rodio = "0.21.1"
serde = "1.0.228"
serde_json = "1.0.148"
vek = "0.17.2"
